### ISSUE TITLE
Email as in built Entity

### ISSUE THREAD

**Issue by jawahar273** [snipsco/snips-nlu-ontology#140]
Hi, 
Could someone help me in finding a best way to parse email id through i could not find entity related to EMAIL, I mean whole text of the email is only returned  partial as show in the example.

> Pardon my English

## Training

```yaml
# entries of list
---
type: entity
name: emailEntity

# data breach
---
type: entity
name: dataBreachEntity
values:
  - pwned
  - data breach
  - compromised
  - hacked


#  Check if you have an account
#  that has been compromised in a data breach
---

type: intent
name: pwnedIntent_global
$class: Pwned
slots:
  - name: email
    entity: emailEntity
  - name: breach
    entity: dataBreachEntity
utterances:
    - have my [email](some@gmap.com) has been [breach](hacked)
    - Check my [email](some@gmap.com) has been [breach](hacked)
    - Is my [email](some@gmap.com) has been [breach](hacked)
    - Can you check my [email](some@gmap.com) has been [breach](hacked)

```

## Output
```bash
# This is not the actual output but one of my test run I found this issue.
is my jon@gil.om  is hacked
```

```json
{
   "input":"is my jon@gil.om  is hacked",
   "intent":{
      "intentName":"pwnedIntent_global",
      "probability":0.4785732421278243
   },
   "slots":[
      {
         "range":{
            "start":6,
            "end":13
         },
         "rawValue":"jon@gil",
         "value":{
            "kind":"Custom",
            "value":"jon@gil"
         },
         "entity":"emailEntity",
         "slotName":"email"
      },
      {
         "range":{
            "start":21,
            "end":27
         },
         "rawValue":"hacked",
         "value":{
            "kind":"Custom",
            "value":"hacked"
         },
         "entity":"dataBreachEntity",
         "slotName":"breach"
      }
   ]
}
```
